### ISSUE TITLE
QVHighlights and YouCook2

### ISSUE THREAD

**Issue by PixelDoodle** [GenjiB/ECLIPSE#5]
Very good job, benefited me a lot.
But when I downloaded the QVHighlights dataset, the speed was very slow, about 20kb/s.
How can I easily obtain this dataset?
Can you upload QVHighlights to Google network disk or other network disks to provide convenient download.
Looking forward to the author's reply, thank you very much.

**Comment by GenjiB** [comment]
Could you contact the authors to see if they provide better ways to download data? 


Or shoot me an email. Let me figure out how it works. Thank you

**Comment by PixelDoodle** [comment]
Sorry, my statement misunderstood you.
Perhaps uploading the compressed file to Google drive, baidu pan (https://pan.baidu.com/pcloud/home) or aliyundrive (https://www.aliyundrive.com/) can be more convenient for researchers to download. The latter two sites have free mass storage.
In addition, the 134GB QVHighlights dataset is compressed into 10 sub-files in batches, which we can download separately.
Thank you very much for your reply! Once again, congratulations on your outstanding achievement. I look forward to reading your future work with great interest and wish you continued success in your academic endeavors.

**Comment by GenjiB** [comment]
I try to upload it in a few days.  Can you contact me through email? that I can send you the link/
