### ISSUE TITLE
Tensor size mismatch when loading with  ViT-b32

### ISSUE THREAD

**Issue by gianlucamacri** [GenjiB/ECLIPSE#9]
I am working on a modified version of the code, but as this issue seems related to the original code I will highlight it for further checks or future reference.

Specifically, the following line of code 
https://github.com/GenjiB/ECLIPSE/blob/0f3bb93a55316facd2872e4a8f05922103ca0383/modules/module_clip.py#L511

seems to be the cause of the following error message when trying to use the model with the ViT-b32 pre-trained model.
```
ERROR -   Weights from pretrained model cause errors in CLIP4Clip: size mismatch for clip.visual.conv_audio.weight: copying a param with shape torch.Size([768, 1, 32, 32]) from checkpoint, the shape in current model is torch.Size([768, 1, 16, 16]).
```

This seems to derive from the following lines
https://github.com/GenjiB/ECLIPSE/blob/0f3bb93a55316facd2872e4a8f05922103ca0383/modules/modeling.py#L97-L99

which adds a key renaming the old `conv1` name into `conv_audio` allowing the loading of the weight of the pre-trained Visual Transformer.

A quick fix to avoid the error message would be to simply use the variable `patch_size` in place of the hardcoded value of 16, to guarantee shape consistency, or to remove the above addition of the key to the state dictionary.

However, as the actual `conv_audio` layer doesn't seem to be used in the `forward` function, even without this change the model would be loading and working fine. So seems more like some old pieces of code that cause no harm other than the error message. I would only like to ask the author to confirm this is the intended behaviour.

**Comment by GenjiB** [comment]
We used to simply apply ViT for audio without visual-only pretrained weights. So, we have this modification.  However, our final version used pretrained audio features.  I forgot to remove this part. You can ignore it.
